apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "semantification.integration:8443"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "https://semantification.integration:8443"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://semantification.integration"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingressHostName }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "app.fullname" . }}
                port:
                  number: 8443
            path: /nifi
            pathType: Prefix
