apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingressHostName }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "app.fullname" . }}
                port:
                  number: 8443
            path: /nifi
            pathType: Prefix
