apiVersion: v1
kind: PersistentVolume
metadata:
  name: uc2-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /tmp/uc2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - semantification-service
