apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uc2-pvc
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
