{{ if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uc2-pvc
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  storageClassName: ""
  volumeName: uc2-pv
