replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8443

resources: {}

livenessProbe:
  httpGet:
    path: /nifi
    port: 8443
    scheme: HTTPS
    host: localhost
readinessProbe:
  httpGet:
    path: /nifi
    port: 8443
    scheme: HTTPS
    host: localhost

ingressHostName: semantification-service
